# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Shell-Autobox
version:      0.02
version_from: lib/Shell/Autobox.pm
installdirs:  perl
requires:
    autobox:                       1.03
    File::Temp:                    0.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
